<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="123707" started-at="2020-10-13T02:12:32 EDT" finished-at="2020-10-13T02:14:36 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="123707" started-at="2020-10-13T02:12:32 EDT" finished-at="2020-10-13T02:14:36 EDT">
      <class name="com.wordpress.tests.KeywordDrivenUsingExcel">
        <test-method status="FAIL" signature="loginToWordpress(java.lang.String, java.lang.String)[pri:0, instance:com.wordpress.tests.KeywordDrivenUsingExcel@71bbf57e]" name="loginToWordpress" duration-ms="76145" started-at="2020-10-13T02:12:32 EDT" data-provider="wordpress" finished-at="2020-10-13T02:13:49 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ã¤dmin1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://demosite.center/wordpress/wp-login.php] but found [http://demosite.center/wordpress/wp-admin/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://demosite.center/wordpress/wp-login.php] but found [http://demosite.center/wordpress/wp-admin/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.wordpress.tests.KeywordDrivenUsingExcel.loginToWordpress(KeywordDrivenUsingExcel.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToWordpress -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.wordpress.tests.KeywordDrivenUsingExcel@71bbf57e]" name="tearDown" is-config="true" duration-ms="886" started-at="2020-10-13T02:13:49 EDT" finished-at="2020-10-13T02:13:49 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="loginToWordpress(java.lang.String, java.lang.String)[pri:0, instance:com.wordpress.tests.KeywordDrivenUsingExcel@71bbf57e]" name="loginToWordpress" duration-ms="17379" started-at="2020-10-13T02:13:49 EDT" data-provider="wordpress" finished-at="2020-10-13T02:14:07 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToWordpress -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.wordpress.tests.KeywordDrivenUsingExcel@71bbf57e]" name="tearDown" is-config="true" duration-ms="11728" started-at="2020-10-13T02:14:07 EDT" finished-at="2020-10-13T02:14:19 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="loginToWordpress(java.lang.String, java.lang.String)[pri:0, instance:com.wordpress.tests.KeywordDrivenUsingExcel@71bbf57e]" name="loginToWordpress" duration-ms="10924" started-at="2020-10-13T02:14:19 EDT" data-provider="wordpress" finished-at="2020-10-13T02:14:30 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://demosite.center/wordpress/wp-login.php] but found [http://demosite.center/wordpress/wp-admin/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://demosite.center/wordpress/wp-login.php] but found [http://demosite.center/wordpress/wp-admin/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.wordpress.tests.KeywordDrivenUsingExcel.loginToWordpress(KeywordDrivenUsingExcel.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToWordpress -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.wordpress.tests.KeywordDrivenUsingExcel@71bbf57e]" name="tearDown" is-config="true" duration-ms="6116" started-at="2020-10-13T02:14:30 EDT" finished-at="2020-10-13T02:14:36 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.wordpress.tests.KeywordDrivenUsingExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
